### ISSUE TITLE
Problem in the structure of conllu

### ISSUE THREAD

**Issue by wellington36** [UniversalDependencies/UD_Romanian-RRT#1]
In branch dev the sentence [train-566](https://raw.githubusercontent.com/UniversalDependencies/UD_Romanian-RRT/dev/ro_rrt-ud-train.conllu), we have 2 tabs before number five:

```
1	Uite	uite	INTJ	I	_		5	discourse	_	SpaceAfter=No
```

**Comment by verginicabm** [comment]
This has been corrected in the new version uploaded in the dev branch.

**Comment by LanguageStructure** [comment]
@wellington36 insere os números p Romanian-RRT
